<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductVariant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Hardware - Gaming PC
            [
                'category_slug' => 'hardware',
                'name' => 'Gear-In Core One',
                'summary' => 'Desktop PC minimalis dengan RTX 4070 dan casing matte hitam.',
                'description' => 'Setup siap pakai dengan fokus pada airflow optimal dan estetika monokrom.',
                'specifications' => [
                    'CPU' => 'Intel Core i7-13700K',
                    'GPU' => 'NVIDIA RTX 4070 12GB',
                    'RAM' => '32GB DDR5-5600',
                    'Storage' => '1TB NVMe SSD + 2TB HDD',
                    'Motherboard' => 'Z790 ATX',
                    'PSU' => '750W 80+ Gold Modular',
                    'Case' => 'Matte Black Mid-Tower',
                    'Cooling' => 'AIO 240mm + 3x Case Fans',
                    'Dimensi' => '450 x 210 x 480 mm',
                    'Berat' => '12.5kg',
                ],
                'price' => 28999000,
                'stock' => 8,
                'is_featured' => true,
            ],
            [
                'category_slug' => 'hardware',
                'name' => 'Gear-In Gaming Pro',
                'summary' => 'PC Gaming high-end dengan RTX 4090 untuk 4K gaming dan streaming.',
                'description' => 'Rig gaming premium dengan komponen terbaik untuk gaming 4K, streaming, dan content creation.',
                'specifications' => [
                    'CPU' => 'Intel Core i9-13900K',
                    'GPU' => 'NVIDIA RTX 4090 24GB',
                    'RAM' => '64GB DDR5-6000',
                    'Storage' => '2TB NVMe SSD Gen4 + 4TB HDD',
                    'Motherboard' => 'Z790 ATX Premium',
                    'PSU' => '1000W 80+ Platinum Modular',
                    'Case' => 'Full Tower RGB',
                    'Cooling' => 'AIO 360mm + 6x RGB Fans',
                    'Dimensi' => '550 x 250 x 550 mm',
                    'Berat' => '18kg',
                ],
                'price' => 45999000,
                'stock' => 5,
                'is_featured' => true,
            ],
            [
                'category_slug' => 'hardware',
                'name' => 'Gear-In Gaming Entry',
                'summary' => 'PC Gaming entry-level untuk 1080p gaming dengan RTX 4060.',
                'description' => 'PC gaming budget-friendly yang tetap powerful untuk gaming 1080p dan productivity.',
                'specifications' => [
                    'CPU' => 'Intel Core i5-13400F',
                    'GPU' => 'NVIDIA RTX 4060 8GB',
                    'RAM' => '16GB DDR4-3200',
                    'Storage' => '512GB NVMe SSD + 1TB HDD',
                    'Motherboard' => 'B760 mATX',
                    'PSU' => '650W 80+ Bronze',
                    'Case' => 'Mid-Tower',
                    'Cooling' => 'Air Cooler + 2x Case Fans',
                    'Dimensi' => '400 x 200 x 450 mm',
                    'Berat' => '10kg',
                ],
                'price' => 14999000,
                'stock' => 15,
            ],
            // Hardware - Workstation
            [
                'category_slug' => 'hardware',
                'name' => 'Gear-In Workstation Pro',
                'summary' => 'Workstation untuk 3D rendering, video editing, dan CAD dengan CPU Threadripper.',
                'description' => 'Workstation profesional dengan CPU AMD Threadripper untuk rendering, video editing, dan CAD yang intensif.',
                'specifications' => [
                    'CPU' => 'AMD Ryzen Threadripper PRO 5975WX (32-core)',
                    'GPU' => 'NVIDIA RTX A5000 24GB',
                    'RAM' => '128GB DDR4 ECC',
                    'Storage' => '4TB NVMe SSD Gen4 + 8TB HDD',
                    'Motherboard' => 'TRX50 WRX80',
                    'PSU' => '1200W 80+ Platinum',
                    'Case' => 'Full Tower Professional',
                    'Cooling' => 'AIO 360mm + 8x Case Fans',
                    'Dimensi' => '600 x 280 x 600 mm',
                    'Berat' => '25kg',
                ],
                'price' => 89999000,
                'stock' => 3,
            ],
            [
                'category_slug' => 'hardware',
                'name' => 'Gear-In Workstation Standard',
                'summary' => 'Workstation untuk design dan development dengan CPU Ryzen 9.',
                'description' => 'Workstation untuk graphic design, software development, dan multimedia production.',
                'specifications' => [
                    'CPU' => 'AMD Ryzen 9 7950X (16-core)',
                    'GPU' => 'NVIDIA RTX 4070 Ti 12GB',
                    'RAM' => '64GB DDR5-5600',
                    'Storage' => '2TB NVMe SSD Gen4 + 4TB HDD',
                    'Motherboard' => 'X670E ATX',
                    'PSU' => '850W 80+ Gold Modular',
                    'Case' => 'Mid-Tower Professional',
                    'Cooling' => 'AIO 280mm + 4x Case Fans',
                    'Dimensi' => '450 x 220 x 500 mm',
                    'Berat' => '15kg',
                ],
                'price' => 34999000,
                'stock' => 6,
            ],
            // Hardware - Server
            [
                'category_slug' => 'hardware',
                'name' => 'Gear-In Server Rack',
                'summary' => 'Server rack untuk hosting, database, dan enterprise applications.',
                'description' => 'Server rack mount dengan dual CPU Xeon untuk hosting, database server, dan enterprise applications.',
                'specifications' => [
                    'CPU' => 'Dual Intel Xeon Silver 4314 (16-core each)',
                    'GPU' => 'Integrated',
                    'RAM' => '256GB DDR4 ECC',
                    'Storage' => '8x 2TB SAS HDD (RAID)',
                    'Motherboard' => 'Server Board Dual Socket',
                    'PSU' => 'Dual 800W Redundant',
                    'Case' => '2U Rack Mount',
                    'Cooling' => 'Server Fans',
                    'Dimensi' => '482 x 88 x 700 mm (2U)',
                    'Berat' => '20kg',
                ],
                'price' => 129999000,
                'stock' => 2,
            ],
            [
                'category_slug' => 'hardware',
                'name' => 'Gear-In Server Tower',
                'summary' => 'Server tower untuk small business dan development server.',
                'description' => 'Server tower untuk small business, development server, dan file server.',
                'specifications' => [
                    'CPU' => 'Intel Xeon E-2388G (8-core)',
                    'GPU' => 'Integrated',
                    'RAM' => '64GB DDR4 ECC',
                    'Storage' => '4x 4TB HDD (RAID) + 1TB SSD',
                    'Motherboard' => 'Server Board',
                    'PSU' => '600W 80+ Gold',
                    'Case' => 'Tower Server',
                    'Cooling' => 'Server Fans',
                    'Dimensi' => '500 x 200 x 550 mm',
                    'Berat' => '18kg',
                ],
                'price' => 49999000,
                'stock' => 4,
            ],
            // Hardware - Office PC
            [
                'category_slug' => 'hardware',
                'name' => 'Gear-In Office Pro',
                'summary' => 'PC Office untuk productivity dengan CPU Intel Core i7.',
                'description' => 'PC office dengan performa tinggi untuk productivity, multitasking, dan business applications.',
                'specifications' => [
                    'CPU' => 'Intel Core i7-13700',
                    'GPU' => 'Intel UHD Graphics 770',
                    'RAM' => '32GB DDR4-3200',
                    'Storage' => '1TB NVMe SSD',
                    'Motherboard' => 'B760 mATX',
                    'PSU' => '500W 80+ Bronze',
                    'Case' => 'SFF (Small Form Factor)',
                    'Cooling' => 'Stock Cooler',
                    'Dimensi' => '350 x 180 x 380 mm',
                    'Berat' => '8kg',
                ],
                'price' => 12999000,
                'stock' => 12,
            ],
            [
                'category_slug' => 'hardware',
                'name' => 'Gear-In Office Standard',
                'summary' => 'PC Office budget untuk daily productivity tasks.',
                'description' => 'PC office ekonomis untuk daily productivity, browsing, dan office applications.',
                'specifications' => [
                    'CPU' => 'Intel Core i5-13400',
                    'GPU' => 'Intel UHD Graphics 730',
                    'RAM' => '16GB DDR4-3200',
                    'Storage' => '512GB NVMe SSD',
                    'Motherboard' => 'H610 mATX',
                    'PSU' => '400W 80+ Bronze',
                    'Case' => 'SFF (Small Form Factor)',
                    'Cooling' => 'Stock Cooler',
                    'Dimensi' => '320 x 170 x 360 mm',
                    'Berat' => '7kg',
                ],
                'price' => 8999000,
                'stock' => 20,
            ],
            [
                'category_slug' => 'hardware',
                'name' => 'Gear-In Office Mini',
                'summary' => 'Mini PC untuk space-saving office setup.',
                'description' => 'Mini PC compact untuk space-saving office setup dengan performa cukup untuk productivity.',
                'specifications' => [
                    'CPU' => 'Intel Core i5-12400',
                    'GPU' => 'Intel UHD Graphics 730',
                    'RAM' => '16GB DDR4-3200',
                    'Storage' => '512GB NVMe SSD',
                    'Motherboard' => 'Mini-ITX',
                    'PSU' => 'External 120W',
                    'Case' => 'Mini-ITX Case',
                    'Cooling' => 'Low-Profile Cooler',
                    'Dimensi' => '200 x 200 x 100 mm',
                    'Berat' => '2.5kg',
                ],
                'price' => 7999000,
                'stock' => 18,
            ],
            
            // Mice
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In Precision Mouse',
                'summary' => 'Mouse 65g dengan sensor 26k DPI dan coating matte.',
                'description' => 'Mouse gaming wireless dengan sensor high-precision, battery 80 jam, dan ergonomic design untuk long gaming sessions.',
                'specifications' => [
                    'Berat' => '65g',
                    'Sensor' => 'PixArt PAW3395 (26,000 DPI)',
                    'Switches' => 'Omron D2FC-F-K (50M clicks)',
                    'Connectivity' => 'Wireless 2.4GHz + Bluetooth 5.0',
                    'Battery' => '80 jam (wireless), 100 jam (Bluetooth)',
                    'Grip Type' => 'Palm, Claw, Fingertip',
                    'Polling Rate' => '1000Hz',
                    'Dimensi' => '126 x 66 x 38 mm',
                ],
                'price' => 1499000,
                'stock' => 40,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Color: Black', 'price_adjustment' => 0, 'stock' => 15],
                    ['name' => 'Color: White', 'price_adjustment' => 50000, 'stock' => 12],
                    ['name' => 'Color: Gray', 'price_adjustment' => 0, 'stock' => 13],
                ]
            ],
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In Ultra Light Mouse',
                'summary' => 'Mouse ultra-lightweight 45g untuk competitive gaming.',
                'description' => 'Mouse dengan honeycomb design, sensor 30k DPI, dan ultra-low latency untuk competitive gaming.',
                'specifications' => [
                    'Berat' => '45g',
                    'Sensor' => 'PixArt PAW3399 (30,000 DPI)',
                    'Switches' => 'Kailh GM 8.0 (80M clicks)',
                    'Connectivity' => 'Wireless 2.4GHz',
                    'Battery' => '70 jam',
                    'Grip Type' => 'Claw, Fingertip',
                    'Polling Rate' => '1000Hz (wireless), 8000Hz (wired)',
                    'Dimensi' => '120 x 64 x 36 mm',
                    'Material' => 'Honeycomb shell dengan coating matte',
                ],
                'price' => 1999000,
                'stock' => 25,
                'variants' => [
                    ['name' => 'Color: Black', 'price_adjustment' => 0, 'stock' => 10],
                    ['name' => 'Color: Red', 'price_adjustment' => 100000, 'stock' => 8],
                    ['name' => 'Color: Blue', 'price_adjustment' => 100000, 'stock' => 7],
                ]
            ],
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In Ergo Mouse',
                'summary' => 'Mouse ergonomic untuk productivity dan long hours.',
                'description' => 'Mouse ergonomic dengan vertical design, mengurangi strain pada pergelangan tangan.',
                'specifications' => [
                    'Berat' => '120g',
                    'Sensor' => 'PixArt PAW3360 (12,000 DPI)',
                    'Switches' => 'Omron D2FC-F-K (20M clicks)',
                    'Connectivity' => 'Wireless 2.4GHz + Bluetooth 5.0',
                    'Battery' => '90 hari',
                    'Grip Type' => 'Palm (vertical)',
                    'Polling Rate' => '1000Hz',
                    'Dimensi' => '110 x 75 x 60 mm',
                    'Fitur' => 'Vertical design, thumb rest, 6 programmable buttons',
                ],
                'price' => 1299000,
                'stock' => 30,
                'variants' => [
                    ['name' => 'Color: Black', 'price_adjustment' => 0, 'stock' => 12],
                    ['name' => 'Color: White', 'price_adjustment' => 0, 'stock' => 18],
                ]
            ],
            
            // Keyboards
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In Silent Mech Keyboard',
                'summary' => 'Keyboard TKL low-noise dengan switch pre-lube.',
                'description' => 'Housing aluminium, keycaps PBT dye-sub, cocok untuk workstation elegan.',
                'specifications' => [
                    'Layout' => 'TKL (87 keys)',
                    'Berat' => '850g',
                    'Mounting' => 'Gasket mount',
                    'Connectivity' => 'USB-C wired',
                    'Switches' => 'Hot-swappable 3-pin/5-pin',
                    'Keycaps' => 'PBT dye-sublimation',
                    'Case Material' => 'Aluminum',
                    'Plate Material' => 'Aluminum',
                    'Backlight' => 'None',
                    'Dimensi' => '360 x 140 x 40 mm',
                ],
                'price' => 2499000,
                'stock' => 25,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Switch: Red (Linear)', 'price_adjustment' => 0, 'stock' => 10],
                    ['name' => 'Switch: Brown (Tactile)', 'price_adjustment' => 0, 'stock' => 8],
                    ['name' => 'Switch: Blue (Clicky)', 'price_adjustment' => 0, 'stock' => 7],
                ]
            ],
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In Compact 65%',
                'summary' => 'Keyboard compact 65% layout untuk space-saving setup.',
                'description' => 'Keyboard mekanikal 65% dengan hot-swappable switches, RGB backlight, dan aluminum case.',
                'specifications' => [
                    'Layout' => '65% (68 keys)',
                    'Berat' => '650g',
                    'Mounting' => 'Top mount',
                    'Connectivity' => 'USB-C wired',
                    'Switches' => 'Hot-swappable 3-pin/5-pin',
                    'Keycaps' => 'PBT double-shot',
                    'Case Material' => 'Aluminum',
                    'Plate Material' => 'Brass',
                    'Backlight' => 'RGB per-key',
                    'Dimensi' => '310 x 110 x 38 mm',
                ],
                'price' => 1899000,
                'stock' => 20,
                'variants' => [
                    ['name' => 'Layout: ANSI', 'price_adjustment' => 0, 'stock' => 12],
                    ['name' => 'Layout: ISO', 'price_adjustment' => 0, 'stock' => 8],
                ]
            ],
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In Wireless Keyboard',
                'summary' => 'Keyboard wireless dengan battery 6 bulan dan low-profile switches.',
                'description' => 'Keyboard wireless dengan koneksi Bluetooth 5.0, battery life hingga 6 bulan, dan design slim.',
                'specifications' => [
                    'Layout' => 'Full-size (104 keys)',
                    'Berat' => '720g',
                    'Mounting' => 'Integrated',
                    'Connectivity' => 'Bluetooth 5.0 + USB-C wired',
                    'Switches' => 'Low-profile mechanical (pre-lubed)',
                    'Keycaps' => 'ABS double-shot',
                    'Case Material' => 'Plastic dengan aluminum top plate',
                    'Battery' => '4000mAh (6 bulan)',
                    'Backlight' => 'White LED',
                    'Dimensi' => '440 x 130 x 25 mm',
                ],
                'price' => 1799000,
                'stock' => 18,
                'variants' => [
                    ['name' => 'Color: Black', 'price_adjustment' => 0, 'stock' => 10],
                    ['name' => 'Color: White', 'price_adjustment' => 0, 'stock' => 8],
                ]
            ],
            
            // IEMs
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In IEM Pro',
                'summary' => 'In-ear monitor dengan dual driver dan detachable cable.',
                'description' => 'IEM dengan dual driver (dynamic + balanced armature), detachable MMCX cable, dan isolation yang baik.',
                'specifications' => [
                    'Driver' => '10mm Dynamic + Balanced Armature',
                    'Impedance' => '16Ω',
                    'Sensitivity' => '108dB/mW',
                    'Frequency Response' => '20Hz - 20kHz',
                    'Cable' => 'Detachable MMCX (1.2m)',
                    'Connector' => '3.5mm (USB-C DAC optional)',
                    'Isolation' => '-26dB',
                    'Housing Material' => 'Aluminum',
                    'Berat' => '12g (per earbud)',
                ],
                'price' => 899000,
                'stock' => 35,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Cable: 3.5mm', 'price_adjustment' => 0, 'stock' => 15],
                    ['name' => 'Cable: USB-C DAC', 'price_adjustment' => 200000, 'stock' => 12],
                    ['name' => 'Cable: Wireless Adapter', 'price_adjustment' => 300000, 'stock' => 8],
                ]
            ],
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In IEM Studio',
                'summary' => 'IEM dengan flat frequency response untuk monitoring.',
                'description' => 'IEM dengan single balanced armature driver, flat frequency response untuk accurate monitoring dan mixing.',
                'specifications' => [
                    'Driver' => 'Single Balanced Armature',
                    'Impedance' => '32Ω',
                    'Sensitivity' => '105dB/mW',
                    'Frequency Response' => '20Hz - 18kHz',
                    'Cable' => 'Detachable MMCX (1.5m)',
                    'Connector' => '3.5mm (Premium Silver optional)',
                    'Isolation' => '-28dB',
                    'Housing Material' => 'Resin custom-molded',
                    'Berat' => '8g (per earbud)',
                    'Sound Signature' => 'Flat/Neutral',
                ],
                'price' => 1299000,
                'stock' => 22,
                'variants' => [
                    ['name' => 'Cable: Standard', 'price_adjustment' => 0, 'stock' => 12],
                    ['name' => 'Cable: Premium Silver', 'price_adjustment' => 500000, 'stock' => 10],
                ]
            ],
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In IEM Gaming',
                'summary' => 'IEM dengan enhanced bass untuk gaming dan music.',
                'description' => 'IEM dengan V-shaped sound signature, enhanced bass untuk gaming, dan detachable cable dengan mic.',
                'specifications' => [
                    'Driver' => '10mm Dynamic',
                    'Impedance' => '16Ω',
                    'Sensitivity' => '110dB/mW',
                    'Frequency Response' => '20Hz - 20kHz',
                    'Cable' => 'Detachable dengan inline mic',
                    'Connector' => '3.5mm',
                    'Isolation' => '-22dB',
                    'Housing Material' => 'Plastic dengan metal accents',
                    'Berat' => '10g (per earbud)',
                    'Sound Signature' => 'V-shaped (Enhanced bass & treble)',
                    'Mic' => 'Omnidirectional dengan noise cancellation',
                ],
                'price' => 699000,
                'stock' => 40,
                'variants' => [
                    ['name' => 'Color: Black', 'price_adjustment' => 0, 'stock' => 15],
                    ['name' => 'Color: Blue', 'price_adjustment' => 0, 'stock' => 12],
                    ['name' => 'Color: Red', 'price_adjustment' => 0, 'stock' => 13],
                ]
            ],
            
            // Headsets
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In Void Wireless Headset',
                'summary' => 'Headset wireless 40h battery dengan ANC adaptif.',
                'description' => 'Driver 40mm custom-tuned dengan sound signature seimbang.',
                'specifications' => [
                    'Driver' => '40mm custom-tuned',
                    'Impedance' => '32Ω',
                    'Frequency Response' => '20Hz - 20kHz',
                    'Connectivity' => 'Bluetooth 5.2 + 3.5mm wired',
                    'Battery' => '40 jam (ANC off), 30 jam (ANC on)',
                    'ANC' => 'Adaptive Active Noise Cancellation',
                    'Mic' => 'Detachable boom mic dengan noise cancellation',
                    'Berat' => '280g',
                    'Dimensi' => '190 x 180 x 85 mm',
                    'Material' => 'Aluminum frame, memory foam earpads',
                ],
                'price' => 1999000,
                'stock' => 15,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Color: Black', 'price_adjustment' => 0, 'stock' => 8],
                    ['name' => 'Color: White', 'price_adjustment' => 100000, 'stock' => 7],
                ]
            ],
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In Studio Headphones',
                'summary' => 'Headphone open-back untuk mixing dan critical listening.',
                'description' => 'Headphone open-back dengan driver 50mm, flat frequency response, dan comfort untuk long sessions.',
                'specifications' => [
                    'Driver' => '50mm dynamic',
                    'Impedance' => '250Ω',
                    'Sensitivity' => '98dB/mW',
                    'Frequency Response' => '10Hz - 25kHz',
                    'Type' => 'Open-back',
                    'Cable' => 'Detachable 3m/1.5m',
                    'Connector' => '3.5mm dengan 6.35mm adapter',
                    'Berat' => '320g',
                    'Dimensi' => '200 x 190 x 100 mm',
                    'Material' => 'Aluminum frame, velour earpads',
                    'Sound Signature' => 'Flat/Neutral untuk monitoring',
                ],
                'price' => 2499000,
                'stock' => 12,
                'variants' => [
                    ['name' => 'Cable: 3m Straight', 'price_adjustment' => 0, 'stock' => 6],
                    ['name' => 'Cable: 1.5m Coiled', 'price_adjustment' => 0, 'stock' => 6],
                ]
            ],
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In Gaming Headset',
                'summary' => 'Headset gaming dengan 7.1 virtual surround dan RGB.',
                'description' => 'Headset gaming dengan driver 50mm, 7.1 virtual surround sound, RGB lighting, dan detachable mic.',
                'specifications' => [
                    'Driver' => '50mm neodymium',
                    'Impedance' => '32Ω',
                    'Frequency Response' => '20Hz - 20kHz',
                    'Connectivity' => 'USB + 3.5mm',
                    'Surround Sound' => '7.1 Virtual Surround',
                    'Mic' => 'Detachable cardioid mic dengan noise cancellation',
                    'RGB' => 'Per-zone RGB lighting (16.8M colors)',
                    'Berat' => '350g',
                    'Dimensi' => '200 x 195 x 95 mm',
                    'Material' => 'Plastic dengan aluminum accents',
                    'Software' => 'Custom software untuk EQ & RGB control',
                ],
                'price' => 1499000,
                'stock' => 28,
                'variants' => [
                    ['name' => 'Color: Black', 'price_adjustment' => 0, 'stock' => 10],
                    ['name' => 'Color: White', 'price_adjustment' => 0, 'stock' => 9],
                    ['name' => 'Color: RGB Edition', 'price_adjustment' => 200000, 'stock' => 9],
                ]
            ],
            
            // Mousepads
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In Speed Mousepad',
                'summary' => 'Mousepad hard surface untuk speed dan precision.',
                'description' => 'Mousepad hard surface dengan low friction untuk fast mouse movements, ukuran XL 900x400mm.',
                'specifications' => [
                    'Surface Type' => 'Hard plastic (low friction)',
                    'Base' => 'Non-slip rubber',
                    'Thickness' => '3mm',
                    'Ukuran' => 'XL: 900 x 400mm (Medium: 450x400mm, Large: 800x400mm)',
                    'Edge' => 'Beveled edges',
                    'Waterproof' => 'Ya',
                    'Maintenance' => 'Easy to clean dengan microfiber',
                ],
                'price' => 399000,
                'stock' => 50,
                'variants' => [
                    ['name' => 'Size: Medium (450x400mm)', 'price_adjustment' => -100000, 'stock' => 20],
                    ['name' => 'Size: Large (800x400mm)', 'price_adjustment' => 0, 'stock' => 15],
                    ['name' => 'Size: XL (900x400mm)', 'price_adjustment' => 50000, 'stock' => 15],
                ]
            ],
            [
                'category_slug' => 'accessories',
                'name' => 'Gear-In Control Mousepad',
                'summary' => 'Mousepad cloth dengan high control untuk precision.',
                'description' => 'Mousepad cloth dengan high friction untuk precise control, stitched edges, dan non-slip base.',
                'specifications' => [
                    'Surface Type' => 'Cloth (high friction)',
                    'Base' => 'Non-slip rubber',
                    'Thickness' => '4mm',
                    'Ukuran' => 'XL: 900 x 400mm (Medium: 450x400mm, Large: 800x400mm)',
                    'Edge' => 'Stitched edges (anti-fray)',
                    'Waterproof' => 'Tidak (water-resistant)',
                    'Maintenance' => 'Hand wash dengan mild soap',
                ],
                'price' => 349000,
                'stock' => 45,
                'variants' => [
                    ['name' => 'Size: Medium', 'price_adjustment' => -100000, 'stock' => 18],
                    ['name' => 'Size: Large', 'price_adjustment' => 0, 'stock' => 15],
                    ['name' => 'Size: XL', 'price_adjustment' => 50000, 'stock' => 12],
                ]
            ],
            
            // Games - Latest Releases 2024/2025
            [
                'category_slug' => 'games',
                'name' => 'Black Myth: Wukong',
                'summary' => 'Action RPG dengan setting Chinese mythology, rilis 2024.',
                'description' => 'Black Myth: Wukong adalah action RPG yang mengambil inspirasi dari novel klasik Journey to the West. Game ini menampilkan combat system yang challenging dengan transformasi karakter, magic abilities, dan boss battles yang epic. Dengan graphics yang stunning menggunakan Unreal Engine 5, game ini menawarkan pengalaman gaming yang immersive dengan storytelling yang mendalam tentang legenda Sun Wukong.',
                'specifications' => [
                    'Platform' => 'PC (Steam/Epic Games), PlayStation 5, Xbox Series X/S',
                    'Genre' => 'Action RPG, Souls-like',
                    'Developer' => 'Game Science',
                    'Publisher' => 'Game Science',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language (Chinese, English, Indonesian subtitles)',
                    'System Requirements' => 'Windows 10, DirectX 12, 16GB RAM, RTX 3060',
                    'Content' => 'Full game',
                ],
                'price' => 699000,
                'stock' => 42,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 25],
                    ['name' => 'Format: PC Digital Key (Epic Games)', 'price_adjustment' => 0, 'stock' => 10],
                    ['name' => 'Format: PlayStation 5 Physical Disc', 'price_adjustment' => 150000, 'stock' => 4],
                    ['name' => 'Format: Xbox Series X/S Physical Disc', 'price_adjustment' => 150000, 'stock' => 3],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Avowed',
                'summary' => 'Action RPG first-person dari Obsidian Entertainment, rilis 2024.',
                'description' => 'Avowed adalah action RPG first-person yang berlatar di dunia Eora, universe yang sama dengan Pillars of Eternity. Game ini menampilkan magic combat system yang unik, dimana pemain dapat menggunakan kombinasi spell dan senjata untuk melawan musuh. Dengan storytelling yang khas Obsidian dan choice-driven narrative, Avowed menawarkan pengalaman RPG yang mendalam dengan multiple endings berdasarkan keputusan pemain.',
                'specifications' => [
                    'Platform' => 'PC (Steam), Xbox Series X/S',
                    'Genre' => 'Action RPG, First-Person',
                    'Developer' => 'Obsidian Entertainment',
                    'Publisher' => 'Xbox Game Studios',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language',
                    'System Requirements' => 'Windows 10, DirectX 12, 16GB RAM, RTX 3060',
                    'Content' => 'Full game',
                ],
                'price' => 799000,
                'stock' => 38,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 20],
                    ['name' => 'Format: PC Digital Key (Xbox/Microsoft Store)', 'price_adjustment' => 0, 'stock' => 10],
                    ['name' => 'Format: Xbox Series X/S Physical Disc', 'price_adjustment' => 100000, 'stock' => 8],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Dragon\'s Dogma 2',
                'summary' => 'Action RPG open world sequel dari Capcom, rilis 2024.',
                'description' => 'Dragon\'s Dogma 2 adalah sequel dari game cult classic yang menampilkan Pawn system yang unik, dimana pemain dapat merekrut AI companions yang dibuat oleh pemain lain. Game ini menawarkan open world yang luas dengan dynamic day/night cycle, berbagai monster mitologi, dan combat system yang memungkinkan pemain untuk memanjat monster besar. Dengan improved graphics dan gameplay mechanics, Dragon\'s Dogma 2 menghadirkan pengalaman adventure yang epic.',
                'specifications' => [
                    'Platform' => 'PC (Steam), PlayStation 5, Xbox Series X/S',
                    'Genre' => 'Action RPG, Open World',
                    'Developer' => 'Capcom',
                    'Publisher' => 'Capcom',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language',
                    'System Requirements' => 'Windows 10, DirectX 12, 16GB RAM, RTX 2070',
                    'Content' => 'Full game',
                ],
                'price' => 899000,
                'stock' => 45,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 20],
                    ['name' => 'Format: PlayStation 5 Physical Disc', 'price_adjustment' => 150000, 'stock' => 12],
                    ['name' => 'Format: Xbox Series X/S Physical Disc', 'price_adjustment' => 150000, 'stock' => 13],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Final Fantasy VII Rebirth',
                'summary' => 'Action RPG sequel Final Fantasy VII Remake, rilis 2024.',
                'description' => 'Final Fantasy VII Rebirth adalah sequel dari Final Fantasy VII Remake yang melanjutkan perjalanan Cloud dan kawan-kawan. Game ini menampilkan open world exploration yang luas, improved combat system dengan materia system yang lebih dalam, dan story yang lebih kompleks. Dengan graphics yang memukau dan soundtrack yang iconic, Rebirth menghadirkan pengalaman RPG yang tak terlupakan dengan multiple story paths dan character development yang mendalam.',
                'specifications' => [
                    'Platform' => 'PlayStation 5',
                    'Genre' => 'Action RPG, Open World',
                    'Developer' => 'Square Enix',
                    'Publisher' => 'Square Enix',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language (Japanese, English, Indonesian subtitles)',
                    'System Requirements' => 'PlayStation 5',
                    'Content' => 'Full game',
                ],
                'price' => 999000,
                'stock' => 35,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Format: PlayStation 5 Physical Disc', 'price_adjustment' => 0, 'stock' => 20],
                    ['name' => 'Format: PlayStation 5 Digital Key', 'price_adjustment' => -50000, 'stock' => 15],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Helldivers 2',
                'summary' => 'Co-op shooter third-person dari Arrowhead Game Studios, rilis 2024.',
                'description' => 'Helldivers 2 adalah co-op shooter third-person yang menampilkan gameplay intense dengan teamwork-focused mechanics. Pemain bekerja sama dalam tim untuk menyelesaikan misi melawan alien forces dengan berbagai senjata dan strategems. Game ini menampilkan friendly fire yang realistis, permadeath mechanics, dan dynamic mission system yang membuat setiap playthrough unik. Dengan graphics yang impressive dan gameplay yang challenging, Helldivers 2 adalah game co-op yang sempurna untuk dimainkan bersama teman.',
                'specifications' => [
                    'Platform' => 'PC (Steam), PlayStation 5',
                    'Genre' => 'Third-Person Shooter, Co-op',
                    'Developer' => 'Arrowhead Game Studios',
                    'Publisher' => 'Sony Interactive Entertainment',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language',
                    'System Requirements' => 'Windows 10, DirectX 12, 8GB RAM, GTX 1050 Ti',
                    'Content' => 'Full game',
                ],
                'price' => 599000,
                'stock' => 50,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 30],
                    ['name' => 'Format: PlayStation 5 Digital Key', 'price_adjustment' => 0, 'stock' => 20],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Like a Dragon: Infinite Wealth',
                'summary' => 'Action RPG dari SEGA dengan setting Hawaii, rilis 2024.',
                'description' => 'Like a Dragon: Infinite Wealth melanjutkan kisah Ichiban Kasuga dengan setting baru di Hawaii. Game ini menampilkan turn-based combat system yang diperbaiki, berbagai mini-games yang menghibur, dan story yang penuh dengan drama dan komedi. Dengan karakter-karakter yang memorable, side quests yang menarik, dan world exploration yang luas, Infinite Wealth menawarkan pengalaman RPG yang lengkap dengan lebih dari 100 jam konten gameplay.',
                'specifications' => [
                    'Platform' => 'PC (Steam), PlayStation 5, Xbox Series X/S',
                    'Genre' => 'Action RPG, Turn-based',
                    'Developer' => 'Ryu Ga Gotoku Studio',
                    'Publisher' => 'SEGA',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language (Japanese, English, Indonesian subtitles)',
                    'System Requirements' => 'Windows 10, DirectX 12, 16GB RAM, RTX 2060',
                    'Content' => 'Full game',
                ],
                'price' => 799000,
                'stock' => 40,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 18],
                    ['name' => 'Format: PlayStation 5 Physical Disc', 'price_adjustment' => 100000, 'stock' => 12],
                    ['name' => 'Format: Xbox Series X/S Physical Disc', 'price_adjustment' => 100000, 'stock' => 10],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Persona 3 Reload',
                'summary' => 'Remake Persona 3 dengan graphics dan gameplay yang diperbarui, rilis 2024.',
                'description' => 'Persona 3 Reload adalah remake lengkap dari Persona 3 dengan graphics modern menggunakan Unreal Engine, improved gameplay mechanics, dan voice acting baru. Game ini menampilkan social simulation elements dimana pemain harus mengelola waktu antara sekolah, social links, dan dungeon crawling. Dengan story yang emotional tentang tema kematian dan kehidupan, Persona 3 Reload menghadirkan pengalaman JRPG yang mendalam dengan character development yang kompleks dan multiple endings.',
                'specifications' => [
                    'Platform' => 'PC (Steam), PlayStation 5, Xbox Series X/S',
                    'Genre' => 'JRPG, Social Simulation',
                    'Developer' => 'Atlus',
                    'Publisher' => 'Atlus',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language (Japanese, English, Indonesian subtitles)',
                    'System Requirements' => 'Windows 10, DirectX 11, 8GB RAM, GTX 1060',
                    'Content' => 'Full game',
                ],
                'price' => 699000,
                'stock' => 48,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 22],
                    ['name' => 'Format: PlayStation 5 Physical Disc', 'price_adjustment' => 100000, 'stock' => 15],
                    ['name' => 'Format: Xbox Series X/S Physical Disc', 'price_adjustment' => 100000, 'stock' => 11],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Tekken 8',
                'summary' => 'Fighting game terbaru dari Bandai Namco, rilis 2024.',
                'description' => 'Tekken 8 adalah fighting game terbaru yang menampilkan roster karakter baru, improved graphics dengan Unreal Engine 5, dan gameplay mechanics yang lebih smooth dengan Heat System yang baru. Game ini menawarkan online multiplayer yang robust dengan rollback netcode, story mode yang cinematic, dan berbagai game modes termasuk Arcade Quest dan Character Customization yang lebih dalam. Dengan combat system yang responsive dan combo system yang kompleks, Tekken 8 adalah fighting game yang sempurna untuk competitive players.',
                'specifications' => [
                    'Platform' => 'PC (Steam), PlayStation 5, Xbox Series X/S',
                    'Genre' => 'Fighting Game',
                    'Developer' => 'Bandai Namco Studios',
                    'Publisher' => 'Bandai Namco',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language',
                    'System Requirements' => 'Windows 10, DirectX 12, 8GB RAM, GTX 1050 Ti',
                    'Content' => 'Full game',
                ],
                'price' => 799000,
                'stock' => 43,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 20],
                    ['name' => 'Format: PlayStation 5 Physical Disc', 'price_adjustment' => 150000, 'stock' => 12],
                    ['name' => 'Format: Xbox Series X/S Physical Disc', 'price_adjustment' => 150000, 'stock' => 11],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Prince of Persia: The Lost Crown',
                'summary' => 'Action-adventure platformer dari Ubisoft, rilis 2024.',
                'description' => 'Prince of Persia: The Lost Crown adalah action-adventure platformer yang kembali ke akar seri dengan time manipulation mechanics yang iconic. Game ini menampilkan combat yang fluid dengan combo system, parkour mechanics yang challenging, dan puzzle-solving elements. Dengan art style yang vibrant dan soundtrack yang atmospheric, The Lost Crown menghadirkan pengalaman platformer yang modern dengan respect terhadap legacy franchise Prince of Persia.',
                'specifications' => [
                    'Platform' => 'PC (Steam/Ubisoft), PlayStation 5, Xbox Series X/S, Nintendo Switch',
                    'Genre' => 'Action-Adventure, Platformer',
                    'Developer' => 'Ubisoft Montpellier',
                    'Publisher' => 'Ubisoft',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language',
                    'System Requirements' => 'Windows 10, DirectX 11, 8GB RAM, GTX 960',
                    'Content' => 'Full game',
                ],
                'price' => 599000,
                'stock' => 52,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 18],
                    ['name' => 'Format: PC Digital Key (Ubisoft)', 'price_adjustment' => 0, 'stock' => 12],
                    ['name' => 'Format: PlayStation 5 Physical Disc', 'price_adjustment' => 100000, 'stock' => 8],
                    ['name' => 'Format: Nintendo Switch Physical Cartridge', 'price_adjustment' => 100000, 'stock' => 14],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Suicide Squad: Kill the Justice League',
                'summary' => 'Action shooter dari Rocksteady Studios, rilis 2024.',
                'description' => 'Suicide Squad: Kill the Justice League adalah action shooter dengan co-op gameplay dari developer Batman Arkham series. Game ini menampilkan 4 playable characters dengan unique abilities, traversal mechanics yang dynamic, dan combat system yang fast-paced. Dengan story yang dark dan humor yang khas Suicide Squad, game ini menawarkan pengalaman co-op yang intense dengan endgame content yang terus berkembang melalui seasonal updates.',
                'specifications' => [
                    'Platform' => 'PC (Steam), PlayStation 5, Xbox Series X/S',
                    'Genre' => 'Action Shooter, Co-op',
                    'Developer' => 'Rocksteady Studios',
                    'Publisher' => 'Warner Bros. Games',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language',
                    'System Requirements' => 'Windows 10, DirectX 12, 16GB RAM, RTX 2070',
                    'Content' => 'Full game',
                ],
                'price' => 899000,
                'stock' => 36,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 18],
                    ['name' => 'Format: PlayStation 5 Physical Disc', 'price_adjustment' => 150000, 'stock' => 10],
                    ['name' => 'Format: Xbox Series X/S Physical Disc', 'price_adjustment' => 150000, 'stock' => 8],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Star Wars Outlaws',
                'summary' => 'Action-adventure open world dari Ubisoft, rilis 2024.',
                'description' => 'Star Wars Outlaws adalah action-adventure open world yang berlatar di Star Wars universe antara Episode V dan VI. Game ini menampilkan space exploration dengan seamless transition antara planet dan space, dynamic reputation system dengan berbagai factions, dan story-driven gameplay dengan choice and consequence. Dengan graphics yang memukau dan attention to detail yang tinggi terhadap Star Wars lore, Outlaws menawarkan pengalaman adventure yang immersive di galaxy far, far away.',
                'specifications' => [
                    'Platform' => 'PC (Steam/Ubisoft), PlayStation 5, Xbox Series X/S',
                    'Genre' => 'Action-Adventure, Open World',
                    'Developer' => 'Ubisoft Massive',
                    'Publisher' => 'Ubisoft',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language',
                    'System Requirements' => 'Windows 10, DirectX 12, 16GB RAM, RTX 2070',
                    'Content' => 'Full game',
                ],
                'price' => 999000,
                'stock' => 40,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 20],
                    ['name' => 'Format: PC Digital Key (Ubisoft)', 'price_adjustment' => 0, 'stock' => 10],
                    ['name' => 'Format: PlayStation 5 Physical Disc', 'price_adjustment' => 150000, 'stock' => 5],
                    ['name' => 'Format: Xbox Series X/S Physical Disc', 'price_adjustment' => 150000, 'stock' => 5],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Metro Awakening',
                'summary' => 'VR game dari 4A Games, rilis 2024.',
                'description' => 'Metro Awakening adalah VR game yang berlatar di universe Metro dengan immersive experience yang memanfaatkan teknologi VR. Game ini menampilkan survival horror elements dengan resource management, stealth mechanics, dan atmospheric storytelling yang khas seri Metro. Dengan graphics yang optimized untuk VR dan gameplay yang designed khusus untuk virtual reality, Metro Awakening menghadirkan pengalaman horror yang intense dan immersive seperti berada di dalam metro tunnels yang gelap.',
                'specifications' => [
                    'Platform' => 'PC VR (Steam), PlayStation VR2',
                    'Genre' => 'VR, Survival Horror, FPS',
                    'Developer' => '4A Games',
                    'Publisher' => 'Deep Silver',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language',
                    'System Requirements' => 'VR Headset, Windows 10, RTX 3060',
                    'Content' => 'Full game',
                ],
                'price' => 799000,
                'stock' => 28,
                'variants' => [
                    ['name' => 'Format: PC VR Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 15],
                    ['name' => 'Format: PlayStation VR2 Digital Key', 'price_adjustment' => 0, 'stock' => 13],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Hades II',
                'summary' => 'Roguelike action game sequel dari Supergiant Games, rilis 2024.',
                'description' => 'Hades II adalah sequel dari game roguelike yang memenangkan berbagai penghargaan. Game ini menampilkan improved combat dengan new weapons dan abilities, new characters dengan unique personalities, dan story yang lebih dalam dengan multiple endings. Dengan art style yang beautiful, soundtrack yang memorable, dan gameplay loop yang addictive, Hades II menghadirkan pengalaman roguelike yang sempurna dengan progression system yang rewarding dan replayability yang tinggi.',
                'specifications' => [
                    'Platform' => 'PC (Steam/Epic Games)',
                    'Genre' => 'Roguelike, Action',
                    'Developer' => 'Supergiant Games',
                    'Publisher' => 'Supergiant Games',
                    'Release Date' => '2024',
                    'Language' => 'Multi-language',
                    'System Requirements' => 'Windows 10, DirectX 11, 4GB RAM, GTX 750 Ti',
                    'Content' => 'Full game',
                ],
                'price' => 499000,
                'stock' => 55,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 30],
                    ['name' => 'Format: PC Digital Key (Epic Games)', 'price_adjustment' => 0, 'stock' => 25],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Baldur\'s Gate 3',
                'summary' => 'RPG fantasy dengan D&D mechanics dan turn-based combat, Game of the Year 2023.',
                'description' => 'Baldur\'s Gate 3 adalah RPG epic yang menggunakan D&D 5th edition mechanics dengan turn-based combat system yang strategic. Game ini menampilkan story yang kompleks dengan choice and consequence yang meaningful, character customization yang mendalam, dan companion system yang memungkinkan pemain untuk membangun relationship dengan berbagai karakter. Dengan graphics yang impressive, voice acting yang excellent, dan gameplay yang immersive, Baldur\'s Gate 3 telah memenangkan berbagai penghargaan termasuk Game of the Year 2023.',
                'specifications' => [
                    'Platform' => 'PC (Steam), PlayStation 5, Xbox Series X/S',
                    'Genre' => 'RPG, Turn-based Strategy',
                    'Developer' => 'Larian Studios',
                    'Publisher' => 'Larian Studios',
                    'Release Date' => '2023',
                    'Language' => 'Multi-language',
                    'System Requirements' => 'Windows 10, DirectX 11, 8GB RAM, GTX 970',
                    'Content' => 'Full game',
                ],
                'price' => 799000,
                'stock' => 45,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 25],
                    ['name' => 'Format: PlayStation 5 Physical Disc', 'price_adjustment' => 150000, 'stock' => 10],
                    ['name' => 'Format: Xbox Series X/S Physical Disc', 'price_adjustment' => 150000, 'stock' => 10],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Cyberpunk 2077: Phantom Liberty',
                'summary' => 'Cyberpunk 2077 dengan expansion Phantom Liberty, rilis 2023.',
                'description' => 'Cyberpunk 2077: Phantom Liberty adalah expansion besar yang menambahkan story baru, area baru, dan berbagai improvements ke base game. Dengan setting di Night City yang dystopian, game ini menampilkan action RPG dengan first-person combat, cyberware customization, dan story yang complex dengan multiple endings. Expansion Phantom Liberty menambahkan spy thriller narrative dengan Idris Elba sebagai karakter utama, new weapons, vehicles, dan gameplay mechanics yang membuat pengalaman Cyberpunk 2077 lebih lengkap.',
                'specifications' => [
                    'Platform' => 'PC (Steam/GOG), PlayStation 5, Xbox Series X/S',
                    'Genre' => 'Action RPG, Open World',
                    'Developer' => 'CD Projekt RED',
                    'Publisher' => 'CD Projekt',
                    'Release Date' => '2023',
                    'Language' => 'Multi-language',
                    'System Requirements' => 'Windows 10, DirectX 12, 12GB RAM, RTX 2060',
                    'Content' => 'Base game + Phantom Liberty DLC',
                ],
                'price' => 899000,
                'stock' => 40,
                'variants' => [
                    ['name' => 'Format: PC Digital Key (Steam)', 'price_adjustment' => 0, 'stock' => 18],
                    ['name' => 'Format: PC Digital Key (GOG)', 'price_adjustment' => 0, 'stock' => 10],
                    ['name' => 'Format: PlayStation 5 Physical Disc', 'price_adjustment' => 150000, 'stock' => 6],
                    ['name' => 'Format: Xbox Series X/S Physical Disc', 'price_adjustment' => 150000, 'stock' => 6],
                ]
            ],
            [
                'category_slug' => 'games',
                'name' => 'Xbox Game Pass Ultimate (1 Month)',
                'summary' => 'Subscription Xbox Game Pass Ultimate untuk 1 bulan.',
                'description' => 'Xbox Game Pass Ultimate memberikan akses ke ratusan game Xbox, PC, dan cloud gaming selama 1 bulan. Subscription ini termasuk Xbox Live Gold untuk online multiplayer, akses ke game library yang terus berkembang dengan game baru setiap bulan, dan cloud gaming untuk bermain di berbagai device. Dengan berbagai game dari indie hingga AAA titles, Game Pass Ultimate adalah cara terbaik untuk mencoba berbagai game tanpa harus membeli secara individual.',
                'specifications' => [
                    'Platform' => 'Xbox, PC, Cloud',
                    'License Type' => 'Subscription (1 Month)',
                    'Games' => 'Hundreds of games',
                    'Features' => 'Xbox Live Gold, Cloud Gaming, PC Games',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Microsoft Official Support',
                ],
                'price' => 149000,
                'stock' => 500,
            ],
            [
                'category_slug' => 'games',
                'name' => 'PlayStation Plus Premium (1 Year)',
                'summary' => 'Subscription PlayStation Plus Premium untuk 1 tahun.',
                'description' => 'PlayStation Plus Premium memberikan akses ke game library yang luas dengan ratusan game untuk PlayStation 5 dan PlayStation 4, online multiplayer, exclusive discounts, dan game trials untuk mencoba game baru sebelum membeli. Subscription ini juga termasuk cloud saves, early access ke game tertentu, dan akses ke classic PlayStation games. Dengan berbagai benefits dan game library yang terus berkembang, PlayStation Plus Premium adalah investasi yang bagus untuk PlayStation gamers.',
                'specifications' => [
                    'Platform' => 'PlayStation 5, PlayStation 4',
                    'License Type' => 'Subscription (1 Year)',
                    'Games' => 'Hundreds of games',
                    'Features' => 'Online Multiplayer, Game Library, Exclusive Discounts',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Sony Official Support',
                ],
                'price' => 3999000,
                'stock' => 200,
            ],
            [
                'category_slug' => 'games',
                'name' => 'Nintendo Switch Online + Expansion Pack (1 Year)',
                'summary' => 'Subscription Nintendo Switch Online dengan Expansion Pack untuk 1 tahun.',
                'description' => 'Nintendo Switch Online + Expansion Pack memberikan akses ke online multiplayer, cloud saves, classic N64 dan SEGA games, dan DLC access untuk berbagai game Nintendo. Subscription ini termasuk akses ke game library classic yang terus berkembang, exclusive offers, dan online features untuk game seperti Mario Kart 8 Deluxe dan Splatoon 3. Dengan Expansion Pack, pemain juga mendapatkan akses ke DLC seperti Animal Crossing: New Horizons Happy Home Paradise.',
                'specifications' => [
                    'Platform' => 'Nintendo Switch',
                    'License Type' => 'Subscription (1 Year)',
                    'Games' => 'Classic N64, SEGA games',
                    'Features' => 'Online Multiplayer, Cloud Saves, DLC Access',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Nintendo Official Support',
                ],
                'price' => 899000,
                'stock' => 300,
            ],
            
            // Digital Products - Windows Keys
            [
                'category_slug' => 'digital-products',
                'name' => 'Microsoft Windows 11 Pro Key',
                'summary' => 'Product key original Windows 11 Pro untuk aktivasi lifetime.',
                'description' => 'Product key original Windows 11 Pro untuk aktivasi lifetime. Key akan dikirim via email setelah pembayaran.',
                'specifications' => [
                    'Product' => 'Windows 11 Pro',
                    'License Type' => 'Retail (Lifetime)',
                    'Activation' => 'Digital License',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Microsoft Official Support',
                    'Compatibility' => 'PC/Laptop dengan TPM 2.0',
                    'Language' => 'Multi-language',
                ],
                'price' => 2499000,
                'stock' => 100,
                'is_featured' => true,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'Microsoft Windows 11 Home Key',
                'summary' => 'Product key original Windows 11 Home untuk aktivasi lifetime.',
                'description' => 'Product key original Windows 11 Home untuk aktivasi lifetime. Key akan dikirim via email setelah pembayaran.',
                'specifications' => [
                    'Product' => 'Windows 11 Home',
                    'License Type' => 'Retail (Lifetime)',
                    'Activation' => 'Digital License',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Microsoft Official Support',
                    'Compatibility' => 'PC/Laptop dengan TPM 2.0',
                    'Language' => 'Multi-language',
                ],
                'price' => 1999000,
                'stock' => 150,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'Microsoft Windows 10 Pro Key',
                'summary' => 'Product key original Windows 10 Pro untuk aktivasi lifetime.',
                'description' => 'Product key original Windows 10 Pro untuk aktivasi lifetime. Key akan dikirim via email setelah pembayaran.',
                'specifications' => [
                    'Product' => 'Windows 10 Pro',
                    'License Type' => 'Retail (Lifetime)',
                    'Activation' => 'Digital License',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Microsoft Official Support',
                    'Compatibility' => 'PC/Laptop',
                    'Language' => 'Multi-language',
                ],
                'price' => 1899000,
                'stock' => 120,
            ],
            
            // Digital Products - Office Keys
            [
                'category_slug' => 'digital-products',
                'name' => 'Microsoft Office 2021 Professional Plus Key',
                'summary' => 'Product key original Office 2021 Professional Plus untuk 1 PC.',
                'description' => 'Product key original Microsoft Office 2021 Professional Plus (Word, Excel, PowerPoint, Outlook, Access, Publisher) untuk 1 PC. Lifetime license.',
                'specifications' => [
                    'Product' => 'Office 2021 Professional Plus',
                    'License Type' => 'Retail (Lifetime)',
                    'Devices' => '1 PC',
                    'Applications' => 'Word, Excel, PowerPoint, Outlook, Access, Publisher',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Microsoft Official Support',
                    'Language' => 'Multi-language',
                ],
                'price' => 3499000,
                'stock' => 80,
                'is_featured' => true,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'Microsoft Office 2021 Home & Student Key',
                'summary' => 'Product key original Office 2021 Home & Student untuk 1 PC.',
                'description' => 'Product key original Microsoft Office 2021 Home & Student (Word, Excel, PowerPoint) untuk 1 PC. Lifetime license.',
                'specifications' => [
                    'Product' => 'Office 2021 Home & Student',
                    'License Type' => 'Retail (Lifetime)',
                    'Devices' => '1 PC',
                    'Applications' => 'Word, Excel, PowerPoint',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Microsoft Official Support',
                    'Language' => 'Multi-language',
                ],
                'price' => 1999000,
                'stock' => 100,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'Microsoft 365 Personal (1 Year)',
                'summary' => 'Subscription Microsoft 365 Personal untuk 1 user, 1 tahun.',
                'description' => 'Subscription Microsoft 365 Personal untuk 1 user dengan 1TB OneDrive storage. Termasuk Office apps dan updates.',
                'specifications' => [
                    'Product' => 'Microsoft 365 Personal',
                    'License Type' => 'Subscription (1 Year)',
                    'Users' => '1 User',
                    'Storage' => '1TB OneDrive',
                    'Applications' => 'Word, Excel, PowerPoint, Outlook, OneNote',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Microsoft Official Support',
                ],
                'price' => 899000,
                'stock' => 200,
            ],
            
            // Digital Products - Adobe
            [
                'category_slug' => 'digital-products',
                'name' => 'Adobe Creative Cloud All Apps (1 Year)',
                'summary' => 'Subscription Adobe Creative Cloud All Apps untuk 1 tahun.',
                'description' => 'Subscription Adobe Creative Cloud All Apps dengan akses ke semua aplikasi Adobe (Photoshop, Illustrator, Premiere Pro, After Effects, dll) untuk 1 tahun.',
                'specifications' => [
                    'Product' => 'Adobe Creative Cloud All Apps',
                    'License Type' => 'Subscription (1 Year)',
                    'Users' => '1 User',
                    'Storage' => '100GB Cloud Storage',
                    'Applications' => 'All Adobe Apps (50+ apps)',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Adobe Official Support',
                ],
                'price' => 8999000,
                'stock' => 50,
                'is_featured' => true,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'Adobe Photoshop (1 Year)',
                'summary' => 'Subscription Adobe Photoshop untuk 1 tahun.',
                'description' => 'Subscription Adobe Photoshop untuk 1 tahun dengan akses ke semua fitur dan updates terbaru.',
                'specifications' => [
                    'Product' => 'Adobe Photoshop',
                    'License Type' => 'Subscription (1 Year)',
                    'Users' => '1 User',
                    'Storage' => '100GB Cloud Storage',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Adobe Official Support',
                ],
                'price' => 2499000,
                'stock' => 80,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'Adobe Premiere Pro (1 Year)',
                'summary' => 'Subscription Adobe Premiere Pro untuk 1 tahun.',
                'description' => 'Subscription Adobe Premiere Pro untuk video editing profesional dengan akses ke semua fitur dan updates terbaru.',
                'specifications' => [
                    'Product' => 'Adobe Premiere Pro',
                    'License Type' => 'Subscription (1 Year)',
                    'Users' => '1 User',
                    'Storage' => '100GB Cloud Storage',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Adobe Official Support',
                ],
                'price' => 2499000,
                'stock' => 70,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'Adobe Illustrator (1 Year)',
                'summary' => 'Subscription Adobe Illustrator untuk 1 tahun.',
                'description' => 'Subscription Adobe Illustrator untuk vector graphics dan design dengan akses ke semua fitur dan updates terbaru.',
                'specifications' => [
                    'Product' => 'Adobe Illustrator',
                    'License Type' => 'Subscription (1 Year)',
                    'Users' => '1 User',
                    'Storage' => '100GB Cloud Storage',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Adobe Official Support',
                ],
                'price' => 2499000,
                'stock' => 75,
            ],
            
            // Digital Products - Autodesk
            [
                'category_slug' => 'digital-products',
                'name' => 'Autodesk AutoCAD (1 Year)',
                'summary' => 'Subscription Autodesk AutoCAD untuk 1 tahun.',
                'description' => 'Subscription Autodesk AutoCAD untuk CAD design dan drafting profesional dengan akses ke semua fitur dan updates terbaru.',
                'specifications' => [
                    'Product' => 'Autodesk AutoCAD',
                    'License Type' => 'Subscription (1 Year)',
                    'Users' => '1 User',
                    'Storage' => '25GB Cloud Storage',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Autodesk Official Support',
                ],
                'price' => 8999000,
                'stock' => 30,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'Autodesk 3ds Max (1 Year)',
                'summary' => 'Subscription Autodesk 3ds Max untuk 1 tahun.',
                'description' => 'Subscription Autodesk 3ds Max untuk 3D modeling, animation, dan rendering dengan akses ke semua fitur dan updates terbaru.',
                'specifications' => [
                    'Product' => 'Autodesk 3ds Max',
                    'License Type' => 'Subscription (1 Year)',
                    'Users' => '1 User',
                    'Storage' => '25GB Cloud Storage',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Autodesk Official Support',
                ],
                'price' => 9999000,
                'stock' => 25,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'Autodesk Revit (1 Year)',
                'summary' => 'Subscription Autodesk Revit untuk 1 tahun.',
                'description' => 'Subscription Autodesk Revit untuk BIM (Building Information Modeling) dan architectural design dengan akses ke semua fitur dan updates terbaru.',
                'specifications' => [
                    'Product' => 'Autodesk Revit',
                    'License Type' => 'Subscription (1 Year)',
                    'Users' => '1 User',
                    'Storage' => '25GB Cloud Storage',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Autodesk Official Support',
                ],
                'price' => 9999000,
                'stock' => 20,
            ],
            
            // Digital Products - Antivirus
            [
                'category_slug' => 'digital-products',
                'name' => 'Kaspersky Total Security (1 Year)',
                'summary' => 'License Kaspersky Total Security untuk 1 PC, 1 tahun.',
                'description' => 'License Kaspersky Total Security dengan proteksi lengkap untuk 1 PC selama 1 tahun. Termasuk antivirus, firewall, dan parental control.',
                'specifications' => [
                    'Product' => 'Kaspersky Total Security',
                    'License Type' => 'Subscription (1 Year)',
                    'Devices' => '1 PC',
                    'Features' => 'Antivirus, Firewall, Parental Control, VPN',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Kaspersky Official Support',
                ],
                'price' => 599000,
                'stock' => 150,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'Norton 360 Deluxe (1 Year)',
                'summary' => 'License Norton 360 Deluxe untuk 5 devices, 1 tahun.',
                'description' => 'License Norton 360 Deluxe dengan proteksi lengkap untuk 5 devices selama 1 tahun. Termasuk antivirus, VPN, dan password manager.',
                'specifications' => [
                    'Product' => 'Norton 360 Deluxe',
                    'License Type' => 'Subscription (1 Year)',
                    'Devices' => '5 Devices',
                    'Features' => 'Antivirus, VPN, Password Manager, Cloud Backup',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Norton Official Support',
                ],
                'price' => 899000,
                'stock' => 120,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'Bitdefender Total Security (1 Year)',
                'summary' => 'License Bitdefender Total Security untuk 5 devices, 1 tahun.',
                'description' => 'License Bitdefender Total Security dengan proteksi lengkap untuk 5 devices selama 1 tahun. Termasuk antivirus, firewall, dan VPN.',
                'specifications' => [
                    'Product' => 'Bitdefender Total Security',
                    'License Type' => 'Subscription (1 Year)',
                    'Devices' => '5 Devices',
                    'Features' => 'Antivirus, Firewall, VPN, Parental Control',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'Bitdefender Official Support',
                ],
                'price' => 799000,
                'stock' => 130,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'ESET Internet Security (1 Year)',
                'summary' => 'License ESET Internet Security untuk 3 devices, 1 tahun.',
                'description' => 'License ESET Internet Security dengan proteksi lengkap untuk 3 devices selama 1 tahun. Termasuk antivirus, firewall, dan anti-phishing.',
                'specifications' => [
                    'Product' => 'ESET Internet Security',
                    'License Type' => 'Subscription (1 Year)',
                    'Devices' => '3 Devices',
                    'Features' => 'Antivirus, Firewall, Anti-Phishing, Banking Protection',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'ESET Official Support',
                ],
                'price' => 699000,
                'stock' => 140,
            ],
            [
                'category_slug' => 'digital-products',
                'name' => 'McAfee Total Protection (1 Year)',
                'summary' => 'License McAfee Total Protection untuk unlimited devices, 1 tahun.',
                'description' => 'License McAfee Total Protection dengan proteksi lengkap untuk unlimited devices selama 1 tahun. Termasuk antivirus, VPN, dan identity protection.',
                'specifications' => [
                    'Product' => 'McAfee Total Protection',
                    'License Type' => 'Subscription (1 Year)',
                    'Devices' => 'Unlimited Devices',
                    'Features' => 'Antivirus, VPN, Identity Protection, Password Manager',
                    'Delivery' => 'Instant via Email',
                    'Support' => 'McAfee Official Support',
                ],
                'price' => 999000,
                'stock' => 110,
            ],
            
            // Consoles
            [
                'category_slug' => 'consoles',
                'name' => 'PlayStation 5',
                'summary' => 'Gaming console generasi terbaru dari Sony dengan SSD ultra-fast.',
                'description' => 'PlayStation 5 dengan SSD ultra-fast, ray tracing support, dan backward compatibility dengan PS4 games.',
                'specifications' => [
                    'CPU' => 'AMD Zen 2 (8-core, 3.5GHz)',
                    'GPU' => 'AMD RDNA 2 (10.28 TFLOPS)',
                    'RAM' => '16GB GDDR6',
                    'Storage' => '825GB NVMe SSD',
                    'Resolution' => 'Up to 4K @ 120fps',
                    'Ray Tracing' => 'Yes',
                    'Backward Compatibility' => 'PS4 games',
                    'Controller' => 'DualSense included',
                    'Dimensi' => '390 x 260 x 104 mm',
                    'Berat' => '4.5kg',
                ],
                'price' => 8999000,
                'stock' => 25,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Model: Standard Edition', 'price_adjustment' => 0, 'stock' => 15],
                    ['name' => 'Model: Digital Edition', 'price_adjustment' => -1500000, 'stock' => 10],
                ]
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'Xbox Series X',
                'summary' => 'Gaming console terkuat dari Microsoft dengan 4K gaming.',
                'description' => 'Xbox Series X dengan performa terkuat untuk 4K gaming, ray tracing, dan backward compatibility dengan semua generasi Xbox.',
                'specifications' => [
                    'CPU' => 'AMD Zen 2 (8-core, 3.8GHz)',
                    'GPU' => 'AMD RDNA 2 (12.15 TFLOPS)',
                    'RAM' => '16GB GDDR6',
                    'Storage' => '1TB NVMe SSD',
                    'Resolution' => 'Up to 4K @ 120fps',
                    'Ray Tracing' => 'Yes',
                    'Backward Compatibility' => 'Xbox, Xbox 360, Xbox One',
                    'Controller' => 'Xbox Wireless Controller included',
                    'Dimensi' => '301 x 151 x 151 mm',
                    'Berat' => '4.45kg',
                ],
                'price' => 7999000,
                'stock' => 20,
                'is_featured' => true,
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'Xbox Series S',
                'summary' => 'Gaming console compact dari Microsoft untuk 1440p gaming.',
                'description' => 'Xbox Series S dengan design compact untuk 1440p gaming, ray tracing, dan backward compatibility.',
                'specifications' => [
                    'CPU' => 'AMD Zen 2 (8-core, 3.6GHz)',
                    'GPU' => 'AMD RDNA 2 (4 TFLOPS)',
                    'RAM' => '10GB GDDR6',
                    'Storage' => '512GB NVMe SSD',
                    'Resolution' => 'Up to 1440p @ 120fps',
                    'Ray Tracing' => 'Yes',
                    'Backward Compatibility' => 'Xbox, Xbox 360, Xbox One',
                    'Controller' => 'Xbox Wireless Controller included',
                    'Dimensi' => '275 x 151 x 63.5 mm',
                    'Berat' => '1.93kg',
                ],
                'price' => 4999000,
                'stock' => 30,
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'Nintendo Switch OLED',
                'summary' => 'Nintendo Switch dengan layar OLED 7 inci dan storage lebih besar.',
                'description' => 'Nintendo Switch OLED dengan layar OLED 7 inci yang lebih cerah, storage 64GB, dan dock dengan LAN port.',
                'specifications' => [
                    'CPU' => 'NVIDIA Tegra X1',
                    'GPU' => 'NVIDIA Maxwell',
                    'RAM' => '4GB',
                    'Storage' => '64GB Internal',
                    'Display' => '7" OLED (1280x720)',
                    'Battery' => '4.5-9 hours',
                    'Connectivity' => 'Wi-Fi, Bluetooth, USB-C',
                    'Controller' => 'Joy-Con included',
                    'Dimensi' => '242 x 102 x 13.9 mm',
                    'Berat' => '420g',
                ],
                'price' => 5999000,
                'stock' => 35,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Color: White', 'price_adjustment' => 0, 'stock' => 18],
                    ['name' => 'Color: Neon Red/Blue', 'price_adjustment' => 0, 'stock' => 17],
                ]
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'Nintendo Switch',
                'summary' => 'Nintendo Switch standard dengan layar LCD 6.2 inci.',
                'description' => 'Nintendo Switch dengan layar LCD 6.2 inci, storage 32GB, dan hybrid design untuk gaming di rumah atau mobile.',
                'specifications' => [
                    'CPU' => 'NVIDIA Tegra X1',
                    'GPU' => 'NVIDIA Maxwell',
                    'RAM' => '4GB',
                    'Storage' => '32GB Internal',
                    'Display' => '6.2" LCD (1280x720)',
                    'Battery' => '2.5-6.5 hours',
                    'Connectivity' => 'Wi-Fi, Bluetooth, USB-C',
                    'Controller' => 'Joy-Con included',
                    'Dimensi' => '239 x 102 x 13.9 mm',
                    'Berat' => '398g',
                ],
                'price' => 4999000,
                'stock' => 40,
                'variants' => [
                    ['name' => 'Color: Neon Red/Blue', 'price_adjustment' => 0, 'stock' => 20],
                    ['name' => 'Color: Gray', 'price_adjustment' => 0, 'stock' => 20],
                ]
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'Nintendo Switch Lite',
                'summary' => 'Nintendo Switch versi handheld-only dengan design compact.',
                'description' => 'Nintendo Switch Lite dengan design compact untuk handheld gaming, layar 5.5 inci, dan harga lebih terjangkau.',
                'specifications' => [
                    'CPU' => 'NVIDIA Tegra X1',
                    'GPU' => 'NVIDIA Maxwell',
                    'RAM' => '4GB',
                    'Storage' => '32GB Internal',
                    'Display' => '5.5" LCD (1280x720)',
                    'Battery' => '3-7 hours',
                    'Connectivity' => 'Wi-Fi, Bluetooth, USB-C',
                    'Controller' => 'Built-in controls',
                    'Dimensi' => '208 x 91 x 13.9 mm',
                    'Berat' => '275g',
                ],
                'price' => 3499000,
                'stock' => 45,
                'variants' => [
                    ['name' => 'Color: Yellow', 'price_adjustment' => 0, 'stock' => 12],
                    ['name' => 'Color: Turquoise', 'price_adjustment' => 0, 'stock' => 11],
                    ['name' => 'Color: Coral', 'price_adjustment' => 0, 'stock' => 11],
                    ['name' => 'Color: Gray', 'price_adjustment' => 0, 'stock' => 11],
                ]
            ],
            
            // Console Accessories - PlayStation
            [
                'category_slug' => 'consoles',
                'name' => 'PlayStation 5 DualSense Controller',
                'summary' => 'Wireless controller untuk PS5 dengan haptic feedback dan adaptive triggers.',
                'description' => 'DualSense controller dengan haptic feedback, adaptive triggers, built-in microphone, dan create button.',
                'specifications' => [
                    'Connectivity' => 'Bluetooth, USB-C',
                    'Battery' => 'Built-in rechargeable',
                    'Features' => 'Haptic Feedback, Adaptive Triggers, Touchpad, Motion Sensor',
                    'Compatibility' => 'PlayStation 5, PC',
                    'Dimensi' => '160 x 66 x 106 mm',
                    'Berat' => '280g',
                ],
                'price' => 899000,
                'stock' => 50,
                'variants' => [
                    ['name' => 'Color: White', 'price_adjustment' => 0, 'stock' => 20],
                    ['name' => 'Color: Black', 'price_adjustment' => 0, 'stock' => 15],
                    ['name' => 'Color: Cosmic Red', 'price_adjustment' => 50000, 'stock' => 8],
                    ['name' => 'Color: Midnight Black', 'price_adjustment' => 50000, 'stock' => 7],
                ]
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'PlayStation 5 HD Camera',
                'summary' => 'HD Camera untuk PS5 dengan dual 1080p lenses untuk streaming.',
                'description' => 'HD Camera dengan dual 1080p lenses untuk streaming dan video chat di PlayStation 5.',
                'specifications' => [
                    'Resolution' => '1080p @ 60fps',
                    'Lenses' => 'Dual 1080p',
                    'Microphone' => 'Built-in stereo',
                    'Mount' => 'PS5 compatible',
                    'Connectivity' => 'USB',
                    'Dimensi' => '186 x 27 x 27 mm',
                    'Berat' => '183g',
                ],
                'price' => 599000,
                'stock' => 30,
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'PlayStation 5 Pulse 3D Wireless Headset',
                'summary' => 'Wireless headset untuk PS5 dengan 3D audio support.',
                'description' => 'Pulse 3D Wireless Headset dengan 3D audio support, dual noise-cancelling microphones, dan battery hingga 12 jam.',
                'specifications' => [
                    'Connectivity' => 'Wireless (USB dongle), 3.5mm',
                    'Battery' => '12 hours',
                    'Audio' => '3D Audio, 40mm drivers',
                    'Microphone' => 'Dual noise-cancelling',
                    'Compatibility' => 'PlayStation 5, PC, Mac, Mobile',
                    'Dimensi' => '190 x 180 x 85 mm',
                    'Berat' => '295g',
                ],
                'price' => 1999000,
                'stock' => 25,
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'PlayStation 5 Media Remote',
                'summary' => 'Remote control untuk PS5 dengan dedicated media buttons.',
                'description' => 'Media Remote untuk PlayStation 5 dengan dedicated buttons untuk Netflix, Disney+, Spotify, dan YouTube.',
                'specifications' => [
                    'Connectivity' => 'Bluetooth',
                    'Battery' => '2x AAA (included)',
                    'Features' => 'Dedicated media buttons, Touchpad',
                    'Compatibility' => 'PlayStation 5',
                    'Dimensi' => '150 x 30 x 15 mm',
                    'Berat' => '85g',
                ],
                'price' => 399000,
                'stock' => 40,
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'PlayStation 5 SSD Expansion (1TB)',
                'summary' => 'NVMe SSD 1TB untuk expand storage PS5.',
                'description' => 'NVMe SSD Gen4 1TB dengan heatsink untuk expand storage PlayStation 5. M.2 2280 format.',
                'specifications' => [
                    'Capacity' => '1TB',
                    'Interface' => 'PCIe Gen4 x4 M.2 NVMe',
                    'Form Factor' => 'M.2 2280',
                    'Read Speed' => 'Up to 7000 MB/s',
                    'Write Speed' => 'Up to 5000 MB/s',
                    'Heatsink' => 'Included',
                    'Compatibility' => 'PlayStation 5',
                ],
                'price' => 2499000,
                'stock' => 20,
                'variants' => [
                    ['name' => 'Brand: Samsung 980 PRO', 'price_adjustment' => 0, 'stock' => 8],
                    ['name' => 'Brand: WD Black SN850', 'price_adjustment' => 0, 'stock' => 7],
                    ['name' => 'Brand: Seagate FireCuda 530', 'price_adjustment' => 200000, 'stock' => 5],
                ]
            ],
            
            // Console Accessories - Xbox
            [
                'category_slug' => 'consoles',
                'name' => 'Xbox Wireless Controller',
                'summary' => 'Wireless controller untuk Xbox Series X/S dengan improved design.',
                'description' => 'Xbox Wireless Controller dengan improved design, textured grip, dan share button untuk capture gameplay.',
                'specifications' => [
                    'Connectivity' => 'Bluetooth, USB-C, Xbox Wireless',
                    'Battery' => '2x AA (not included) atau rechargeable',
                    'Features' => 'Share Button, Textured Grip, 3.5mm Headset Jack',
                    'Compatibility' => 'Xbox Series X/S, Xbox One, PC, Mobile',
                    'Dimensi' => '159 x 105 x 62 mm',
                    'Berat' => '287g',
                ],
                'price' => 799000,
                'stock' => 60,
                'variants' => [
                    ['name' => 'Color: Carbon Black', 'price_adjustment' => 0, 'stock' => 20],
                    ['name' => 'Color: Robot White', 'price_adjustment' => 0, 'stock' => 15],
                    ['name' => 'Color: Shock Blue', 'price_adjustment' => 50000, 'stock' => 10],
                    ['name' => 'Color: Electric Volt', 'price_adjustment' => 50000, 'stock' => 8],
                    ['name' => 'Color: Pulse Red', 'price_adjustment' => 50000, 'stock' => 7],
                ]
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'Xbox Elite Wireless Controller Series 2',
                'summary' => 'Premium wireless controller dengan customizable components.',
                'description' => 'Xbox Elite Wireless Controller Series 2 dengan customizable thumbsticks, paddles, dan hair trigger locks untuk competitive gaming.',
                'specifications' => [
                    'Connectivity' => 'Bluetooth, USB-C, Xbox Wireless',
                    'Battery' => 'Built-in rechargeable (40 hours)',
                    'Features' => 'Customizable Thumbsticks, Paddles, Hair Trigger Locks, Adjustable Tension',
                    'Compatibility' => 'Xbox Series X/S, Xbox One, PC',
                    'Dimensi' => '159 x 105 x 62 mm',
                    'Berat' => '345g',
                ],
                'price' => 2999000,
                'stock' => 15,
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'Xbox Wireless Headset',
                'summary' => 'Wireless headset untuk Xbox dengan spatial audio support.',
                'description' => 'Xbox Wireless Headset dengan spatial audio support, dual-mic noise suppression, dan battery hingga 15 jam.',
                'specifications' => [
                    'Connectivity' => 'Xbox Wireless, Bluetooth',
                    'Battery' => '15 hours',
                    'Audio' => 'Spatial Audio, 40mm drivers',
                    'Microphone' => 'Dual-mic noise suppression',
                    'Compatibility' => 'Xbox Series X/S, Xbox One, PC, Mobile',
                    'Dimensi' => '190 x 180 x 85 mm',
                    'Berat' => '312g',
                ],
                'price' => 1499000,
                'stock' => 35,
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'Xbox Storage Expansion Card (1TB)',
                'summary' => 'Storage expansion card 1TB untuk Xbox Series X/S.',
                'description' => 'Storage Expansion Card 1TB dengan performa identik dengan internal storage untuk Xbox Series X/S.',
                'specifications' => [
                    'Capacity' => '1TB',
                    'Interface' => 'Custom NVMe',
                    'Read Speed' => 'Up to 2400 MB/s',
                    'Write Speed' => 'Up to 1900 MB/s',
                    'Form Factor' => 'Custom card',
                    'Compatibility' => 'Xbox Series X/S',
                ],
                'price' => 3999000,
                'stock' => 18,
            ],
            
            // Console Accessories - Nintendo Switch
            [
                'category_slug' => 'consoles',
                'name' => 'Nintendo Switch Pro Controller',
                'summary' => 'Pro Controller untuk Switch dengan design ergonomic dan battery panjang.',
                'description' => 'Pro Controller dengan design ergonomic, HD rumble, motion controls, dan battery hingga 40 jam.',
                'specifications' => [
                    'Connectivity' => 'Bluetooth, USB-C',
                    'Battery' => '40 hours',
                    'Features' => 'HD Rumble, Motion Controls, NFC (Amiibo)',
                    'Compatibility' => 'Nintendo Switch, PC',
                    'Dimensi' => '156 x 116 x 68 mm',
                    'Berat' => '246g',
                ],
                'price' => 899000,
                'stock' => 45,
                'variants' => [
                    ['name' => 'Color: Black', 'price_adjustment' => 0, 'stock' => 25],
                    ['name' => 'Color: Splatoon 3 Edition', 'price_adjustment' => 100000, 'stock' => 10],
                    ['name' => 'Color: Xenoblade Chronicles 3 Edition', 'price_adjustment' => 100000, 'stock' => 10],
                ]
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'Nintendo Switch Joy-Con (Pair)',
                'summary' => 'Joy-Con controller pair untuk Nintendo Switch.',
                'description' => 'Joy-Con pair dengan motion controls, HD rumble, dan detachable design untuk multiplayer gaming.',
                'specifications' => [
                    'Connectivity' => 'Bluetooth',
                    'Battery' => '20 hours (Left), 20 hours (Right)',
                    'Features' => 'HD Rumble, Motion Controls, IR Motion Camera, NFC (Amiibo)',
                    'Compatibility' => 'Nintendo Switch',
                    'Dimensi' => '102 x 35.8 x 28.4 mm (each)',
                    'Berat' => '52g (each)',
                ],
                'price' => 899000,
                'stock' => 50,
                'variants' => [
                    ['name' => 'Color: Neon Red/Blue', 'price_adjustment' => 0, 'stock' => 15],
                    ['name' => 'Color: Neon Yellow', 'price_adjustment' => 0, 'stock' => 12],
                    ['name' => 'Color: Neon Pink/Green', 'price_adjustment' => 0, 'stock' => 13],
                    ['name' => 'Color: Gray', 'price_adjustment' => 0, 'stock' => 10],
                ]
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'Nintendo Switch Carrying Case',
                'summary' => 'Carrying case untuk Nintendo Switch dengan protection.',
                'description' => 'Carrying case dengan hard shell protection, game card storage, dan space untuk accessories.',
                'specifications' => [
                    'Material' => 'Hard shell EVA',
                    'Storage' => 'Game card slots (8-10), Accessories pocket',
                    'Compatibility' => 'Nintendo Switch, Switch OLED',
                    'Dimensi' => '280 x 130 x 60 mm',
                    'Berat' => '350g',
                ],
                'price' => 299000,
                'stock' => 80,
                'variants' => [
                    ['name' => 'Design: Mario', 'price_adjustment' => 50000, 'stock' => 20],
                    ['name' => 'Design: Zelda', 'price_adjustment' => 50000, 'stock' => 20],
                    ['name' => 'Design: Plain Black', 'price_adjustment' => 0, 'stock' => 40],
                ]
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'Nintendo Switch Screen Protector',
                'summary' => 'Tempered glass screen protector untuk Nintendo Switch.',
                'description' => 'Tempered glass screen protector dengan 9H hardness, anti-fingerprint coating, dan easy installation.',
                'specifications' => [
                    'Material' => 'Tempered Glass',
                    'Hardness' => '9H',
                    'Thickness' => '0.33mm',
                    'Features' => 'Anti-fingerprint, Anti-glare, Bubble-free',
                    'Compatibility' => 'Nintendo Switch, Switch OLED, Switch Lite',
                    'Package' => '2x Screen protectors + Installation kit',
                ],
                'price' => 149000,
                'stock' => 100,
            ],
            [
                'category_slug' => 'consoles',
                'name' => 'Nintendo Switch MicroSD Card (256GB)',
                'summary' => 'MicroSD card 256GB untuk expand storage Nintendo Switch.',
                'description' => 'MicroSD card 256GB dengan speed tinggi untuk expand storage Nintendo Switch. Class 10, UHS-I.',
                'specifications' => [
                    'Capacity' => '256GB',
                    'Speed Class' => 'Class 10, UHS-I',
                    'Read Speed' => 'Up to 100 MB/s',
                    'Write Speed' => 'Up to 90 MB/s',
                    'Format' => 'MicroSDXC',
                    'Compatibility' => 'Nintendo Switch',
                ],
                'price' => 399000,
                'stock' => 60,
                'variants' => [
                    ['name' => 'Brand: SanDisk', 'price_adjustment' => 0, 'stock' => 25],
                    ['name' => 'Brand: Samsung', 'price_adjustment' => 0, 'stock' => 20],
                    ['name' => 'Brand: Nintendo Licensed', 'price_adjustment' => 50000, 'stock' => 15],
                ]
            ],
        ];

        foreach ($products as $productData) {
            $category = Category::whereSlug($productData['category_slug'])->first();

            if (! $category) {
                continue;
            }

            $variants = $productData['variants'] ?? [];
            unset($productData['variants']);

            $productDataToSave = Arr::except($productData, ['category_slug', 'variants']);
            $productDataToSave['category_id'] = $category->id;
            $productDataToSave['slug'] = Str::slug($productData['name']);
            $productDataToSave['sku'] = $productData['sku'] ?? strtoupper(Str::random(8));
            $productDataToSave['image_path'] = $productData['image_path'] ?? 'https://placehold.co/800x800/111111/FFFFFF?text=gear-in';
            $productDataToSave['is_active'] = true;
            
            // Ensure specifications is stored as array (not JSON string)
            if (isset($productDataToSave['specifications']) && is_array($productDataToSave['specifications'])) {
                // Already an array, keep as is
            } else {
                // If it's a string, try to decode it
                if (isset($productDataToSave['specifications']) && is_string($productDataToSave['specifications'])) {
                    $productDataToSave['specifications'] = json_decode($productDataToSave['specifications'], true);
                }
            }

            $product = Product::updateOrCreate(
                ['name' => $productData['name']],
                $productDataToSave
            );

            // Create variants if any
            if (!empty($variants)) {
                foreach ($variants as $variantData) {
                    ProductVariant::updateOrCreate(
                        [
                            'product_id' => $product->id,
                            'name' => $variantData['name'],
                        ],
                        [
                            'price_adjustment' => $variantData['price_adjustment'] ?? 0,
                            'stock' => $variantData['stock'] ?? 0,
                            'is_active' => true,
                        ]
                    );
                }
            }
        }
    }
}
